#!/usr/bin/env bash
#
# Check if a specific VPN is up
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: July 03, 2018
# License: MIT

name=$1

[[ -n $name ]] || exit 1

line=$(nmcli -t --color=no con show --active | \
    awk -v "name=$name" -F: '$1 == name && $3 == "vpn"')

[[ -n $line ]]
