#!/usr/bin/env bash
#
# Print the current SSID and VPN connection (used for xfce4-panel genmon)
#
# Author: Dave Eddy <dave@daveeddy.com>
# Date: July 03, 2018
# License: MIT

PATH=~/bin:$PATH

name=$1

[[ -n $name ]] || exit 1

ssid=$(current-ssid)

vpn=''
if vpn-enabled "$name"; then
	vpn=' (vpn)'
fi

echo "$ssid$vpn"
